### ISSUE TITLE
Fix breaking version change in aws-cli during circleci pipeline

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-deployable-node-backend#24]
Version 1.19.45 of `aws-cli` introduced a breaking change that won't work with Python 2.7, which is what the exectuor was using for the `build_and_push` step. This will require the following changes:

Bump the `aws-cli` orb to version 2.0.0:
```yaml
orbs:
  aws-cli: circleci/aws-cli@2.0.0
```

Change the executor for the `build_and_push` job to use python 3:
```yaml
  build_and_push:
    executor: aws-eks/python3
```

Add a new first step to the `build_and_push` job to enable using docker from within a docker container during the build:
```yaml
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
```
